# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ViewComponents::DateTime`.
# Please instead update this file by running `bin/tapioca dsl ViewComponents::DateTime`.


class ViewComponents::DateTime
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
