# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ViewComponents::ErrorMessage`.
# Please instead update this file by running `bin/tapioca dsl ViewComponents::ErrorMessage`.


class ViewComponents::ErrorMessage
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
