# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ViewComponents::FormInput`.
# Please instead update this file by running `bin/tapioca dsl ViewComponents::FormInput`.


class ViewComponents::FormInput
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
