# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ViewComponents::OrderCard`.
# Please instead update this file by running `bin/tapioca dsl ViewComponents::OrderCard`.


class ViewComponents::OrderCard
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
