# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ViewComponents::ProductCard`.
# Please instead update this file by running `bin/tapioca dsl ViewComponents::ProductCard`.


class ViewComponents::ProductCard
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
