# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ViewComponents::TextInput`.
# Please instead update this file by running `bin/tapioca dsl ViewComponents::TextInput`.


class ViewComponents::TextInput
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
