# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Telegram::Bot::UpdatesController::MessageContext`.
# Please instead update this file by running `bin/tapioca dsl Telegram::Bot::UpdatesController::MessageContext`.


module Telegram::Bot::UpdatesController::MessageContext
  mixes_in_class_methods ::Telegram::Bot::UpdatesController::Session::ClassMethods
end
